In [ ]:


# Face Recognition

# Importing the libraries
from PIL import Image
from tensorflow.keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from tensorflow.keras.models import load_model
import numpy as np

from tensorflow.keras.preprocessing import image
model = load_model('facefeatures_new_model_new28052020.h5')

# Loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

def face_extractor(img):
    # Function detects faces and returns the cropped face
    # If no face detected, it returns the input image
    
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    
    if faces is ():
        return None
    
    # Crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]

    return cropped_face

# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    #canvas = detect(gray, frame)
    #image, face =face_detector(frame)
    
    face=face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face, 'RGB')
           #Resizing into 128x128 because we trained the model with this image size.
        img_array = np.array(im)
                    #Our keras model used a 4D tensor, (images x height x width x channel)
                    #So changing dimension 128x128x3 into 1x128x128x3 
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
                     
        name="None matching"
        
        if(pred[0][0]>0.5):
            name='Sailesh'
        elif(pred[0][1]>0.5): 
            name='Shivani'
            
        cv2.putText(frame,name, (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    else:
        cv2.putText(frame,"No face found", (50, 50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2)
    cv2.imshow('Video', frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

       



[[5.3006887e-12 1.0000000e+00]]
[[1.0000000e+00 2.9929753e-37]]
[[1.0000000e+00 4.7342054e-29]]
[[1. 0.]]
[[1. 0.]]
[[1.00000000e+00 1.12219776e-35]]
[[3.379746e-14 1.000000e+00]]
[[0.0010352 0.9989648]]
[[1.8260147e-05 9.9998176e-01]]
[[1. 0.]]
[[1.0000000e+00 1.2344587e-37]]
[[1.00000e+00 6.53233e-35]]
[[1.0000000e+00 3.8405188e-38]]
[[1.0000000e+00 1.1098913e-25]]
[[1.0000000e+00 3.1932426e-31]]
[[1.0000000e+00 2.2346072e-38]]
[[4.566265e-38 1.000000e+00]]
[[1.9005344e-16 1.0000000e+00]]
[[1.998448e-16 1.000000e+00]]
[[6.2373948e-15 1.0000000e+00]]
[[3.744576e-12 1.000000e+00]]
[[1.7682515e-13 1.0000000e+00]]
[[4.469964e-13 1.000000e+00]]
[[1.4667544e-09 1.0000000e+00]]
[[1.6438592e-07 9.9999988e-01]]
[[1.2260422e-25 1.0000000e+00]]
[[0.1347586 0.8652414]]
[[0.9585147  0.04148528]]
[[1.000000e+00 7.548659e-30]]
[[1.0000000e+00 1.2270806e-33]]
[[1.0000000e+00 2.6432668e-37]]
[[1.0000000e+00 2.2345065e-29]]
[[1.000000e+00 2.360521e-31]]
[[1.0000000e+00 2.2050505e-19]]
[[6.346743e-16 1